### ISSUE TITLE
Could you allow to set labels on issues?

### ISSUE THREAD

**Issue by viboes** [boost-experimental/msm-lite#28]
This will allow to state if it is an enhancement, a bug, something related to desig or document only?

**Comment by krzysztof-jusiak** [comment]
added doc, design, test and ci. All github defaults labels are enabled too (bug, etc...)

**Comment by viboes** [comment]
It seems that only you can set labels :(

**Comment by krzysztof-jusiak** [comment]
should work now

**Comment by Bagira80** [comment]
If it once worked, it does no longer work.

At least as a non-owner of the repository I am unable to set any labels. (But maybe this is desired...?)
