### ISSUE TITLE
Change the namespace as boost::msm is already used and msm-lite is not a sublibrary of msm

### ISSUE THREAD

**Issue by viboes** [boost-experimental/msm-lite#34]
You can not use boost::msm::lite as boost::msm is already reserved and your library don't integrates in MSM. I suggest msm_lite or boost::sml  (as state machine lite) or yasm (yet another state machine) something else.

**Comment by krzysztof-jusiak** [comment]
Changed to boost.sml with 0e179a8d848cae59f265b688c9984386dd9959e9, thanks for a great name @viboes! I will transfer the library to sml repo on github, just has to verify whether old docs will be redirected too.

I really like it as it might be interpreted as.
* State Machine Lite
* State Machine Language
* State Machine Library
