### ISSUE TITLE
Doesn't compile with gcc-6

### ISSUE THREAD

**Issue by vlichevsky** [boost-experimental/msm-lite#42]
When trying to compile [this example](https://github.com/boost-experimental/msm-lite/blob/master/example/hello_world.cpp) I get the following error:
`g++-6 -std=c++14 hello_world.cpp -o hello_world`

> In file included from hello_world.cpp:8:0:
boost/msm-lite.hpp: In static member function ‘static bool boost::msm::lite::v_1_0_0::detail::transition_sub_impl<TSM, T, Ts ...>::execute(SM&, const TEvent&, boost::msm::lite::v_1_0_0::aux::byte&)’:
boost/msm-lite.hpp:968:126: error: parameter packs not expanded with ‘...’:
                                                               : transition_impl<T, Ts...>::execute(self, event, current_state);
                                                                                                                          ^
boost/msm-lite.hpp:968:126: note:         ‘decltype(auto)’
boost/msm-lite.hpp: In static member function ‘static bool boost::msm::lite::v_1_0_0::detail::transition_sub_impl<TSM>::execute(SM&, const TEvent&, boost::msm::lite::v_1_0_0::aux::byte&)’:
boost/msm-lite.hpp:975:61: error: parameter packs not expanded with ‘...’:
     return aux::try_get<TSM>(self.deps_).process_event(event);
                                                             ^
boost/msm-lite.hpp:975:61: note:         ‘decltype(auto)’
boost/msm-lite.hpp: In constructor ‘boost::msm::lite::v_1_0_0::detail::sm< <template-parameter-1-1> >::sm(TDeps&& ...)’:
boost/msm-lite.hpp:1152:107: error: parameter packs not expanded with ‘...’:
                                                           transitions_(aux::try_get<SM>(deps_).configure()) {
                                                                                                           ^
boost/msm-lite.hpp:1152:107: note:         ‘decltype(auto)’
boost/msm-lite.hpp: In constructor ‘boost::msm::lite::v_1_0_0::detail::sm< <template-parameter-1-1> >::sm(boost::msm::lite::v_1_0_0::detail::sm< <template-parameter-1-1> >::deps_t&&)’:
boost/msm-lite.hpp:1156:117: error: parameter packs not expanded with ‘...’:
   explicit sm(deps_t &&deps) BOOST_MSM_LITE_NOEXCEPT : deps_(deps), transitions_(aux::try_get<SM>(deps_).configure()) {
                                                                                                                     ^
boost/msm-lite.hpp:1156:117: note:         ‘decltype(auto)’
boost/msm-lite.hpp: In member function ‘void boost::msm::lite::v_1_0_0::detail::sm< <template-parameter-1-1> >::update_composite_states(const boost::msm::lite::v_1_0_0::aux::type_list<TStates ...>&, ...)’:
boost/msm-lite.hpp:1317:37: error: parameter packs not expanded with ‘...’:
     auto &sm = aux::try_get<T>(deps_);
                                                            ^
boost/msm-lite.hpp:1317:37: note:         ‘decltype(auto)’
boost/msm-lite.hpp: In member function ‘void boost::msm::lite::v_1_0_0::detail::sm< <template-parameter-1-1> >::update_composite_states(const boost::msm::lite::v_1_0_0::aux::type_list<>&, const true_type&, const boost::msm::lite::v_1_0_0::aux::type_list<TStates ...>&)’:
boost/msm-lite.hpp:1326:37: error: parameter packs not expanded with ‘...’:
     auto &sm = aux::try_get<T>(deps_);
                                     ^
boost/msm-lite.hpp:1326:37: note:         ‘decltype(auto)’
boost/msm-lite.hpp: In member function ‘void boost::msm::lite::v_1_0_0::detail::sm< <template-parameter-1-1> >::update_composite_states(const boost::msm::lite::v_1_0_0::aux::type_list<>&, const false_type&, ...)’:
boost/msm-lite.hpp:1335:70: error: parameter packs not expanded with ‘...’:
     aux::try_get<T>(deps_).initialize(typename T::initial_states_t{});
                                                                      ^
boost/msm-lite.hpp:1335:70: note:         ‘decltype(auto)’
In file included from hello_world.cpp:8:0:
boost/msm-lite.hpp: In instantiation of ‘boost::msm::lite::v_1_0_0::aux::pool<Ts>::pool(boost::msm::lite::v_1_0_0::aux::init&&, boost::msm::lite::v_1_0_0::aux::pool<TArgs ...>&&) [with TArgs = {}; Ts = {hello_world}]’:
boost/msm-lite.hpp:1152:107:   required from ‘boost::msm::lite::v_1_0_0::detail::sm< <template-parameter-1-1> >::sm(TDeps&& ...) [with TDeps = {}; typename boost::msm::lite::v_1_0_0::aux::enable_if<boost::msm::lite::v_1_0_0::aux::is_same<boost::msm::lite::v_1_0_0::aux::bool_list<boost::msm::lite::v_1_0_0::aux::always<TDeps>::value ...>, boost::msm::lite::v_1_0_0::aux::bool_list<boost::msm::lite::v_1_0_0::aux::integral_constant<bool, __is_base_of(boost::msm::lite::v_1_0_0::aux::pool_type<TDeps>, typename boost::msm::lite::v_1_0_0::aux::apply<boost::msm::lite::v_1_0_0::aux::pool, typename boost::msm::lite::v_1_0_0::aux::join<typename boost::msm::lite::v_1_0_0::aux::conditional<boost::msm::lite::v_1_0_0::aux::integral_constant<bool, __is_trivially_constructible(T)>::value, boost::msm::lite::v_1_0_0::aux::type_list<T>, boost::msm::lite::v_1_0_0::aux::type_list<SM&> >::type, typename boost::msm::lite::v_1_0_0::aux::apply<boost::msm::lite::v_1_0_0::detail::get_sub_sms, typename boost::msm::lite::v_1_0_0::aux::apply<boost::msm::lite::v_1_0_0::aux::unique_t, typename boost::msm::lite::v_1_0_0::aux::apply<boost::msm::lite::v_1_0_0::detail::get_states, decltype((declval<SM>)().configure())>::type>::type>::type, typename boost::msm::lite::v_1_0_0::aux::apply<boost::msm::lite::v_1_0_0::detail::merge_deps, decltype((declval<SM>)().configure())>::type>::type>::type)>::value ...> >::value, int>::type <anonymous> = 0; SM = hello_world]’
hello_world.cpp:39:24:   required from here
boost/msm-lite.hpp:269:97: error: mismatched argument pack lengths while expanding ‘boost::msm::lite::v_1_0_0::aux::pool_type<Ts>’
   pool(init &&, pool<TArgs...> &&p) BOOST_MSM_LITE_NOEXCEPT : pool_type<Ts>{aux::try_get<Ts>(p)}... {}

Compiler version:
`g++-6 --version`
>g++-6 (Debian 6.1.1-1) 6.1.1 20160430
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by krzysztof-jusiak** [comment]
Thanks @vlichevsky for reporting that and sorry about it. Travis doesn't support gcc-6.1 yet, so it's hard to keep track with it.

Anyway, it should be fixed by https://github.com/boost-experimental/msm-lite/commit/ca4ce25c03da43e159e7e385937c4673cd830472

It was compiling fine on gcc-5.2/gcc-5.3/gcc-6.0 however, gcc-6.1 has introduced this issue. IMHO it's gcc bug related to decltype(auto) and variadic templates as it does work on clang properly. I will verify that and report it on gcc bugzilla if appropriate.

**Comment by vlichevsky** [comment]
Commit ca4ce25 indeed fixes the issue. Thanks for quick response.
