### ISSUE TITLE
[question] refer to all known states

### ISSUE THREAD

**Issue by jacquelinekay** [boost-experimental/msm-lite#45]
Hello, I just picked up msm-lite and I'm really looking forward to integrating it into my project, but I couldn't figure out if this feature that I want exists based on the documentation and examples.

I want to specify a transition that can occur from any states in a state machine, results from the same event, has the same side effects, and transitions to the same final state. Is there special syntax in msm-lite for this, to avoid copying the same logic for each transition?

For example, if the "final" state occurs when the "terminate" event occurs from state s1, s2, or s3, this is what I'd like to do... Even better would be a way to refer to all states without listing them all.

```
make_transition_table(
  s1 + e1 / [](){ } = s2,
  /* ... other transitions ... */ ,
  s1 | s2 | s3 + terminate / [](){ /* cleanup for terminate */} = final
);
```

**Comment by krzysztof-jusiak** [comment]
Thanks @jacquelinekay for the question. 
v1.01 doesn't have a notion of `any` state. It could be potentially implemented and at some point I was trying this idea out (_ + terminate = final, where _ was 'any' state), however, it was causing more problems than solutions, so I dropped the idea as it wasn't UML compliant as well.

Having said that, it's possible to achieve what you described quite easily via introducing another orthogonal region, which would look something like that...

```cpp
make_transition_table(
  s1 + e1 / [](){ } = s2,
  /* ... other transitions ... */ ,
 *wait_for_terminate + terminate / [](){ /* cleanup for terminate */} = X
 // * means that it's another orthogonal region
);
```

then you can check whether sm is terminated or not via...

```cpp
assert(sm.is(X)); //if any of region is in X state
```

**Comment by jacquelinekay** [comment]
Thanks for the tip, I'll try using orthogonal regions!
