### ISSUE TITLE
msm-lite is not thread safe

### ISSUE THREAD

**Issue by sirzooro** [boost-experimental/msm-lite#47]
Documentation states that msm-lite is thread-safe where it is not. When two threads send events to the same FSM, actions are executed in parallel, and current state of FSM is overwritten. Please update documentation to state this.

If you plan to update code to make it thread-safe, please allows to create both thread-safe and thread-unsafe FSMs - synchronization is an overhead which is not always needed or wanted.

**Comment by krzysztof-jusiak** [comment]
Thanks @sirzooro for pointing that out. It should be fxied by https://github.com/boost-experimental/msm-lite/commit/5dd2691696eb818b62484512116b9215e5700402 and it has to be turned on by defining BOOST_MSM_LITE_THREAD_SAFE. By default msm-lite is not thread safe. I updated the spec too. Currently the implemention is a blocking one using a simple mutex. I'm investigating whether non-blocking approach is possible.

**Comment by sirzooro** [comment]
Thanks. BTW, what do you think about alternative solution - passing lock object to constructor, in similar way as allocators are passed to STL containers? By By default null lock would be used (structure with empty lock() and unlock() methods), but user could pass alternative implementation. This also would allow sharing single lock by FSM(s) and other parts of code. User could also synchronize only selected FSMs.

**Comment by krzysztof-jusiak** [comment]
done by `tread_safe` policy...

```cpp
test process_event_reentrant = [] {
  struct c {
    auto operator()() const {
      using namespace msm;
      return make_transition_table(
         *"idle"_s + event<e1> / queue(e2{})
        , "idle"_s + event<e2> = "s2"_s
      );
    }
  };

  // thread safe policy allows to define and pass it too
  msm::sm<c, msm::thread_safe<std::recursive_mutex>> sm;
  sm.process_event(e1{});
};
```
