### ISSUE TITLE
Internal events deadlock issue

### ISSUE THREAD

**Issue by feltech** [boost-experimental/msm-lite#61]
Consider the following from the "transitions" example:
```
"s1"_s + event<e2> / ([] { std::cout << "process internal event" << std::endl; }, process_event(e3{})) = X
```
If `BOOST_MSM_LITE_THREAD_SAFE` is enabled, then the above `process_event` call tries to re-acquire the mutex that has already been acquired (by the same thread) in the previous `process_event`, resulting in deadlock.

I found that a find-and-replace of `std::mutex` for the reentrant `std::recursive_mutex` fixes this.

_I would submit a PR, but I suspect `msm-lite.hpp` is generated somehow (would be interested to know what tool is used)?_

**Comment by krzysztof-jusiak** [comment]
Thanks @feltech for reporting this issue.

Feel free to submit the PR, just please, remember to add appropriate tests too. Thanks :)

Anyway, msm-ilte.hpp is actually not generated yet :(.
msm-lite requires a lot of TLC from my side as I didn't have too much time to work on it recently :(
Additionally, https://github.com/boost-experimental/di/blob/cpp14/tools/pph.sh will be adopted to use with msm-lite.

BTW. Eventually, a great suggestion made by @sirzooro will be implemented. Long story short, one will be able to pass a locking object via msm constructor (https://github.com/boost-experimental/msm-lite/issues/47).

**Comment by feltech** [comment]
I believe this issue can now be closed after the commits above.
