### ISSUE TITLE
How to handle unexpected event

### ISSUE THREAD

**Issue by freak82** [boost-experimental/msm-lite#66]
Hi,

The library provides a mechanics for handling unexpected events according to the documentation.

        make_transition_table(
         *"idle"_s + event<my_event> [ guard ] / action = "s1"_s
        ...
        // terminate (=X) the Machine or reset to another state
        ,*"error_handler"_s + unexpected_event<some_event> = X
        );

What exactly should be the 'some_event' in the example above? I mean, I need to handle any event which is not handled. Should I explicitly describe all events in this case?

However, I'm unable to make this compile

              return make_transition_table                                        
                  (                                                               
                      *"idle"_s + event<ev_async_write> / on_async_write{} = "pending_write"_s,
                      "idle"_s + event<ev_cancel> = X,                            
                      "pending_write"_s + event<ev_cancel> / on_cancel{} = X,        
                      *"err_handler"_s + unexpected_event<ev_unknown> / on_unexpected{} = X   
                  );  

Note that the needed event structures (ev_...) and action handlers (on_...) are defined as expected. The problem doesn't come from them. I mean, the compilation problem comes from the last row. I'm not sure if the unexpected_event feature is fully supported at the moment? As far as I can see from the source code of the msm-lite there is  unexpected_event in the detail namespace and that's it.

If the unexpected_event feature is not fully supported, is there a way to handle unexpected events somehow? It's important for my case to handle unexpected events in an explicit way.

Thanks,
Pavel.

**Comment by krzysztof-jusiak** [comment]
Hi @freak82, sorry for the late response. unexpected_event wasn't handled properly :(
I fixed it on master, however, there is a quite big refactor going on there as well, sorry about that.
Anyway, an unexpected event should be handled properly there.
To handle, a generic version of unexpected event you can write `unexpected_event<>`, however, you won't have the event type for it.

```cpp
          return make_transition_table                                        
              (                                                               
                  *"idle"_s + event<ev_async_write> / on_async_write{} = "pending_write"_s,
                  "idle"_s + event<ev_cancel> = X,                            
                  "pending_write"_s + event<ev_cancel> / on_cancel{} = X,        
                  *"err_handler"_s + unexpected_event<> / on_unexpected{} = X   
              );  
```

More examples here:
https://github.com/boost-experimental/msm-lite/blob/master/test/ft/ft_unexpected_events.cpp

I'm going to close this issue as I'm trying to clean them up. Hence, please, reopen if it won't work for you.
